name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.

  call-reuseable-workflow:
    uses: ./.github/workflows/reuseable-workflow.yml
    with:
      node: 14
